### ISSUE TITLE
Include of non modular header 

### ISSUE THREAD

**Issue by ali-nawaz-dev** [OpenClemson/SwiftECP#2]
Hi,

I am trying to use SwiftECP client with an application, I am developing. I have installed pods what require to use SwiftECP but after installation xcode is giving me error of "Include of non modular header", As I searched over internet, they asked to put YES to Non modular header in build setting but that is not working. Can you please guide if we are doing some thing wrong?

Thanks in advance.

**Comment by ali-nawaz-dev** [comment]
Just built with a lower version xcode 7 and it was working.

**Comment by tptee** [comment]
Yeah, I haven't updated this to the latest Swift. I'm hoping to get to another release within the month!
