### ISSUE TITLE
IDP3 requires request to have Content-Type: text/xml

### ISSUE THREAD

**Issue by nawatts** [OpenClemson/SwiftECP#7]
See https://wiki.shibboleth.net/confluence/display/IDP30/IDP3+ECP+with+Tomcat+and+Apache-Managed+Authentication

> Note that for IDP 3, all the test scripts have been modified to set the content type header to text/xml.  This is because curl by default will set an inappropriate content type application/x-www-form-urlencoded) that IDP 2 would tolerate, but IDP 3 will not.

The content type is currently set to `application/vnd.paos+xml` ([ECP.swift#L193](https://github.com/OpenClemson/SwiftECP/blob/c0cb560a4fb8bddd2de6ade31183817782cf2ff8/Pod/Classes/ECP.swift#L193)), so I'm not sure how IDP3 will respond to that.

**Comment by tptee** [comment]
Last I remember, `application/vnd.paos+xml` is what actually triggers the ECP profile, but maybe Tomcat/Apache complicates this?

**Comment by nawatts** [comment]
[It has to send that header to the SP](http://docs.oasis-open.org/security/saml/Post2.0/saml-ecp/v2.0/cs01/saml-ecp-v2.0-cs01.html#_Toc366664721).

**Comment by tptee** [comment]
That makes sense :+1:

**Comment by twstokes** [comment]
[Fixed](https://github.com/OpenClemson/SwiftECP/blob/swift3/Pod/Source/IDPRequest.swift#L102)
